# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Deployment definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  labels:
      tags.datadoghq.com/env: "tsreenv"
      tags.datadoghq.com/service: "cartservice"
      tags.datadoghq.com/version: "0.5.0"  
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
        tags.datadoghq.com/env: "tsreenv"
        tags.datadoghq.com/service: "cartservice"
        tags.datadoghq.com/version: "0.5.0"
        admission.datadoghq.com/enabled: "true"
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - all
          privileged: false
          # readOnlyRootFilesystem: true
        image: public.ecr.aws/v6x4t1k2/cartservice:tsre.v0.5.0
        ports:
        - containerPort: 7070
        env:
        - name: DD_ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/env']
        - name: DD_SERVICE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/service']
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/version']
        - name: DD_TRACE_AGENT_URL
          value: "unix:///var/run/datadog/apm.socket"
        - name: REDIS_ADDR
          value: "redis-cart:6379"
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_TRACE_SAMPLE_RATE
          value: "1"
        - name: DD_RUNTIME_METRICS_ENABLED
          value: "true"
        volumeMounts:
        - name: apmsocketpath
          mountPath: /var/run/datadog        
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
        # readinessProbe:
        #   initialDelaySeconds: 15
        #   exec:
        #     command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]
        # livenessProbe:
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        #   exec:
        #     command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]
      volumes:
        - hostPath:
            path: /var/run/datadog/
          name: apmsocketpath
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  type: ClusterIP
  selector:
    app: cartservice
  ports:
  - name: grpc
    port: 7070
    targetPort: 7070
